### PR TITLE
Micropub tests and fixes, oauth tests, revert htmx, and some other fixes

### PR DESCRIPTION
**Pull request by 1dom**
Apologies for the  large PR. A few things addressed in this:

 - remove HTMx (#12 )
 - added the admin_edit_button macro back in, in the new location, fixing issues with the recent edit post PR (#11)
 - added basic micropub update support
 - added some tests for micropub
 - added some tests for oauth
 - custom html page routes: added a fix, test and docs for using that
 - refactored some of the template shuffling of csrf embedding (`as context` on the import means we don't have to pass the csrf value around everywhere manually)
 - fixed a hardcoded JD link in the footer
 - set MICROPUB_CONFIG_FILE=tests.toml directly in pytest to prevent blowing away DB if tests aren't run via inv
 - some linting

I'd recommend testing this. I cherry picked a few commits from  my main branch, so I haven't tested it thoroughly without my other changes.

(Edit: just did some catching up on discussion, some of these commits are definitely redundant, happy to remove some completely, or split some out into separate PRs)

### CODE REVIEW

**Comment by nigini** [comment]
Awesome stuff, @1dom!
Would it be too much to ask you to revisit this pull request after I integrate the changes I presented in issue #11?
Or did you see anything in my version of the `edit_post` that your code does better?

**Comment by nigini** [comment]
Hey @1dom: I have created a new branch for the changes related to the `v2.1` that I think would be a better place for you to go ahead and revisit your pull request. I am particularly excited about your refactoring and test work. :)

**Comment by 1dom** [comment]
Hi - sure, didn't realise I'd put it up against main, sorry🤦! I just switched it to compare against that branch v2.1 you mentioned, so will fix conflicts etc.

Not sure regarding edit post: any chance you could link to the main commit for that? I'm struggling to follow. FWIW, I only did some fixes just to get the homepage working (so test just to verify that the homepage loads correctly if a user is logged in, and some CSRF fixes to make the test pass) and then saw your discussion/fixes after. I've not fully digested yours yet, I don't think there's a huge amount of functional difference between ours though: you favour explicitly passing CSRF round as a param, whereas in mine, I pass it implicitly using `with context` in the import. I think mine is easier to write and remember, but yours is probably more correct (more explicit and not passing around extra unused context).

 I did some "edit post" type stuff by attaching the micropub endpoint to the update function. But all the stuff I've been doing has been from the micropub/api side: I've not really paid any attention to editing view the UI or edit buttons other than to get stuff loading.



Another challenge I face with this PR and #12 is that I now understand HTMX a bit better, and it seems the intent is pretty nicely aligned (specifically trying keep the focus on hypertext and not on Javascript) and I can totally see how it could be a sensible balance/compromise. I can see the value it would add to micropub. (Although if we do keep it, we should find a some form other than bulk minified JS, ideally without dragging in JS toolchain, if possible).

Either way, I'll split this PR into a few different ones, target v2.1-dev, probably something like:
1. micropub update support
2. custom html route & docs
3. oauth tests
4. remove htmx
5. tidy up footer

Then can all be reviewed individually.

**Comment by nigini** [comment]
> Hi - sure, didn't realise I'd put it up against main, sorry🤦! I just switched it to compare against that branch v2.1 you mentioned, so will fix conflicts etc.

No worries at all. I believe I only thought to create the branch after your PR.

> Not sure regarding edit post: any chance you could link to the main commit for that? I'm struggling to follow. FWIW, I only did some fixes just to get the homepage working (so test just to verify that the homepage loads correctly if a user is logged in, and some CSRF fixes to make the test pass) and then saw your discussion/fixes after. I've not fully digested yours yet, I don't think there's a huge amount of functional difference between ours though: you favour explicitly passing CSRF round as a param, whereas in mine, I pass it implicitly using `with context` in the import. I think mine is easier to write and remember, but yours is probably more correct (more explicit and not passing around extra unused context).
> I did some "edit post" type stuff by attaching the micropub endpoint to the update function. But all the stuff I've been doing has been from the micropub/api side: I've not really paid any attention to editing view the UI or edit buttons other than to get stuff loading.

It sounds like the current code is doing a little more than what you worked on for the edit stuff. Why don't you leave it out of your PR? What I did [HERE](https://github.com/microblog-pub/microblog.pub/commit/20617d9ce6a556e0909bb99bd924b0d190d6ebec) was to integrate work from 778a0a by using the current code standard in `admin.py` and HTML templates. (all changes can be seen in the top 4 commits [HERE](https://github.com/microblog-pub/microblog.pub/commits/edit_post/).)

> Another challenge I face with this PR and #12 is that I now understand HTMX a bit better, and it seems the intent is pretty nicely aligned (specifically trying keep the focus on hypertext and not on Javascript) and I can totally see how it could be a sensible balance/compromise. I can see the value it would add to micropub. (Although if we do keep it, we should find a some form other than bulk minified JS, ideally without dragging in JS toolchain, if possible).

I'd recommend bringing this up in a discussion before making that decision. I personally would like to learn more about what you learned on HTMLX vs JS for this project.

> Either way, I'll split this PR into a few different ones, target v2.1-dev, probably something like:
> 
>     1. micropub update support
> 
>     2. custom html route & docs
> 
>     3. oauth tests
> 
>     4. remove htmx
> 
>     5. tidy up footer
> 
> Then can all be reviewed individually.

Yeah. It would be easier to have a conversation about it.

**Pull request closed without merging**
